name: Pull request
on: 
  pull_request:
    branches:
      -  master
jobs:
 test:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - name: Setup - Xcode
       run: sudo xcode-select -s /Applications/Xcode_12.3.app
     - name: Setup - Ruby and bundler dependencies
       uses: ruby/setup-ruby@v1.57.0
       with:
          ruby-version: 2.4.0
          bundler-cache: true
     - name: Test - Fastlane tests
       run: bundle exec fastlane test
