name: Pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 test:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - name: Setup - Xcode
       run: sudo xcode-select -s /Applications/Xcode_12.3.app
     - uses: actions/checkout@v2
     - uses: actions/setup-ruby@v1
       with:
        ruby-version: '3.0.2'
     - uses: maierj/fastlane-action@v2.0.1
       with:
        lane: 'beta'

     - name: Test - Fastlane tests
       run: bundle exec fastlane test
